
name: Azure Web App Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Build
      run: |
        npm run build
        cp web.config dist/
        
    - name: Check build output
      run: |
        echo "Node version:"
        node -v
        echo "NPM version:"
        npm -v
        echo "Current directory:"
        pwd
        echo "Files in current directory:"
        ls -la
        echo "Build output files:"
        ls -la dist/
        echo "Package.json content:"
        cat package.json
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'friendly-copy-crafter'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './dist'
