
name: Azure Web App Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: friendly-copy-crafter    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'dist'           # set this to the path to your web app project built output
  NODE_VERSION: '20.x'                        # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Clear npm cache
      run: npm cache clean --force
      
    - name: npm install
      run: npm install
      
    - name: npm build
      run: npm run build --verbose
      
    - name: Debug environment
      if: always()
      run: |
        echo "Node version:"
        node --version
        echo "NPM version:" 
        npm --version
        echo "Directory structure:"
        ls -la
        echo "Build output:"
        ls -la dist || echo "No dist directory found"

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        if-no-files-found: error

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: List downloaded files
      run: ls -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
