
name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Configuration des permissions
permissions:
  contents: write
  pages: write
  id-token: write

# Définir des variables d'environnement pour le workflow
env:
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          
      - name: Install dependencies
        run: |
          npm ci || npm install --legacy-peer-deps --ignore-scripts
        
      - name: Build
        run: npm run build
        env:
          CI: false
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true

  # Ajout d'une tâche spécifique pour GitHub Pages
  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
